spring:
# 파일을 변경하면 웹에 바로 적용 
  devtools:
    livereload:
      enabled: true
# HikariCP 이용
  datasource: 
    hikari: 
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
      jdbc-url: jdbc:mysql://localhost:3306/scott?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      
# 쿼리 로그          
  jpa:
    show-sql: true
# 포트변경              
server:
  port: 80




#    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver    

#spring:
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      password: 1234
#      username: root
#  devtools:
#    livereload:
#      enabled: true
#  jpa:
#    show-sql: true
    